### ISSUE TITLE
'paste' removes text and doesn't paste

### ISSUE THREAD

**Issue by poof86** [caphodel/brackets-additional-right-click-menu#1]
I'm using Brackets Release 1.3 build 1.3.0-16022 on Mac OSX 10.10.2
When I copy text and try to paste, it only removes text at the cursor. This doesn't happen when I use 'cut' instead of 'copy'. Oh and paste works fine when I use the keyboard shortcut to copy first.

Seems that this happens only when I'm editing in PHP files :/

**Comment by caphodel** [comment]
I'm not yet installed Brackets ver. 1.3 yet, so I can't try/check this bug right now. I'll check it when I'm home tonight. Thanks for the notify me about this bug :)

**Comment by caphodel** [comment]
@poof86 Like u said, I find some bug for pasting text. I already fixed it, but I don't know if it is fixing the bug on Mac, since I don't have a Mac here. Can u test it by download it and manually install it from my github repo?

Thanks before

**Comment by poof86** [comment]
I installed your latest update through brackets and the bug has been resolved :+1:
Very fast response, thanks!

**Comment by caphodel** [comment]
Your welcome :smile:
