### ISSUE TITLE
Feature Request: Re-Indent

### ISSUE THREAD

**Issue by poof86** [caphodel/brackets-additional-right-click-menu#2]
Not sure where to put requests on git, but wouldn't it be great to have a re-indent option in the right-click-menu? I'm currently using the auto indent after pasting extension in brackets, but a right-click option would be so much easier! :)

**Comment by caphodel** [comment]
Did you mean indent and unindent in the edit menu? If it is that, I could add it in the right click menu.

**Comment by poof86** [comment]
I mean that the selection gets indented automatically based on enclosures and that kind of code structuring.

**Comment by caphodel** [comment]
I already add some functionality called fix indentation, please try it by downloading from github, I want to know if it is what you need. Sorry for the slow response, coz I had a long weekend :smile:

**Comment by poof86** [comment]
We all have a life to live and you are crazy fast with your updates! So shush and enjoy my gratitude for adding this features because it works great :smile:

**Comment by caphodel** [comment]
Thanks, after some other bug fixing I'll send the update to brackets registry.
