### ISSUE TITLE
Key assignment of 'Ctrl+L' causes Brackets console error

### ISSUE THREAD

**Issue by mitorez** [caphodel/brackets-additional-right-click-menu#4]
The automatic key assignment of 'Ctrl+L' by this extension causes a Brackets console error because it conflicts with the Brackets 'core' key assignment of 'Ctrl+L' for 'Select Line'. Thanks.

Windows 7 SP1 Enterprise
Brackets 1.3
Brackets Additional Right Click Menu 0.4.1

**Comment by caphodel** [comment]
Thanks for notify me about it, I'll fixed it as fast as I can, please wait for it.

**Comment by caphodel** [comment]
I already change it's short code to Ctrl+Shift+L, please check it if it's still make a trouble with other key assignment since there is so many extension that could be use it, and there is no doc for making key assignment easy to not conflicted with other extension (or at least, i don't know about it :smile:)

**Comment by mitorez** [comment]
Your 0.5.1 release fixed the issue, thanks for the quick turnaround @caphodel. For a list of the Brackets 'core' shortcut keys, see here: https://github.com/adobe/brackets/wiki/Brackets-Shortcuts. The 'Ctrl+L' shortcut was conflicting with the 'core' Brackets code, not another extension. Thanks again - very helpful extension.

**Comment by mitorez** [comment]
I forgot, the 'Beautify' extension uses 'Ctrl+Shift+L'. I know you won't be able to account for all extensions, so I don't have a good answer on how best to correctly resolve this issue. I haven't written an extension yet, so I don't know where in the extension developer section it documents best practices for shortcut key mapping.

**Comment by caphodel** [comment]
Yes, the problem is it could be conflicted with another extensions short cut key. Well, I have an idea to make an interface to set short cut key, maybe in the next update I will be able to deliver it.
